### ISSUE TITLE
Unity ARCore Reconstruction Plugin Compile Error

### ISSUE THREAD

**Issue by alexs7** [lvonasek/binary#1]
Hello,

I got the asset from Unity Asset store, but I am running into compilation error as seen below:

![Screenshot 2019-04-19 at 14 47 38](https://user-images.githubusercontent.com/1533281/56427074-6cc41000-62b2-11e9-9411-41961eb8699e.png)

> Assets/3DR4ARCore/Scripts/ReconstructionManager.cs(213,17): error CS0103: The name `LifecycleManager' does not exist in the current context

So the samples will not compile. I got some apk's for here but I was wondering why this error is happening and how I can fix it?

Thanks

**Comment by lvonasek** [comment]
There is a readme where is written how you should configure Unity - your issue is indicating that there is missing the define "HAS_GOOGLE_ARCORE".

I am closing this issue but feel free to ask something more.

**Comment by alexs7** [comment]
Thanks, it compiles now great, but I get this, when I start the app:

![Screenshot_20190419-160318](https://user-images.githubusercontent.com/1533281/56430006-d6491c00-62bc-11e9-9f49-5d5c0dc1ef1a.png)

I am on Unity 2018.2.12f1

**Comment by lvonasek** [comment]
Did you do everything from here:
https://drive.google.com/open?id=1KFJTWOfsGNAICaO96PZdc_NZP1LpN8Kg
?

**Comment by alexs7** [comment]
I will watch this and let you know! Thanks again
